version: "3"

services:
  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/vendor
    depends_on:
      - php
    networks:
      - smartbin-network

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
      - ./:/var/www
      - ./.env:/var/www/.env
    depends_on: 
      - postgres
    networks:
      - smartbin-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=smartbin
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432" # Port PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=smartbin
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - smartbin-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80" # pgAdmin sera accessible sur le port 5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@smartbin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    depends_on:
      - postgres
    networks:
      - smartbin-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  smartbin-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: # Volume pour pgAdmin
